---
title: "Antibody Preprocessing"
author: "CBT & Ritchie Lab"
date: today
format: dashboard
knitr:
    opts_knit:
        root.dir: '../'
---

```{r}
# Install package
library(tidyverse)
library(vroom)
library(data.table)
library(ggplot2)
library(ggiraph)
library(plotly)
library(formattable)
library(DT)
```

# Aligned Reads

```{r}
# Read in data
#| include: false

# Get list of files
files <- list.files(
    path = "./results/1_aligned_reads/stats",
    pattern = "\\.tsv$",
    full.names = TRUE
)

# Read in files
data_list <- lapply(files, fread, na.strings = c("N/A"))
# Add in barcode from file name as id col
names(data_list) <- str_replace(basename(files), "_alignment_stats.tsv", "")

# Combine datasets together and rename columns
combined_aligned_stats <- rbindlist(data_list, idcol = "sample_id", fill = TRUE)
combined_aligned_stats <- rename(combined_aligned_stats,
    "QC_pass" = V1, "QC_fail" = V2, "category" = V3
)

# Rename and extract required rows
rows_required <- list("total", "mapped", "mapped %", "primary", "secondary", "supplementary")
combined_aligned_stats <- combined_aligned_stats %>%
    mutate(category = ifelse(category == "total (QC-passed reads + QC-failed reads)",
        "total", category
    )) %>%
    select(-QC_fail) %>%
    mutate(QC_pass, ifelse(str_detect(QC_pass, "%"),
        as.numeric(str_replace(QC_pass, "%", "")),
        as.numeric(QC_pass)
    )) %>%
    filter(category %in% rows_required)

combined_aligned_stats_wide <- combined_aligned_stats %>%
    pivot_wider(
        id_cols = sample_id,
        names_from = category,
        values_from = QC_pass
    )
```

## Row 
```{r}
#| content: valuebox
#| title: "Samples"
samples <- combined_aligned_stats %>%
    distinct(sample_id) %>%
    summarise(n = n()) %>%
    as.numeric()

list(
    icon = "file-earmark-medical",
    color = "info",
    value = samples
)
```

```{r}
#| content: valuebox
#| title: "Total reads"
total_reads <- sum(as.numeric(combined_aligned_stats_wide$total))

list(
    icon = "file-earmark-medical",
    color = "info",
    value = total_reads
)
```

## Row {.flow}

```{r}
#| title: plot 1
#| padding: 0px
#| eval: false

data <- mtcars
data$carname <- row.names(data)

gg_point <- ggplot(data = data) +
    geom_point_interactive(aes(
        x = wt, y = qsec, color = disp,
        tooltip = carname, data_id = carname
    )) +
    theme_minimal()

girafe(ggobj = gg_point)
```

::: {.card title="My Title"}
This text will be displayed within a card
:::

# Extracted reads

## Row {.fill}

```{R}
#| title: Plot 2

```

```{R}
#| title: Plot 3

```

# Annotated reads

## Row {.fill}